# Stream-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

# This is the developer default version. In pipelines, this is driven by versionary.
VERSION=43.dev
BUILDER_IMG=quay.io/bootc-devel/fedora-bootc-43-standard@sha256:2e79e3ad4f701e7e527add054f0fe54b88f2a0e1d0d3081771578fb532d47d98
MANIFEST=manifest.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=manifests
NAME=fedora-coreos
STREAM=testing-devel
DESCRIPTION=Fedora CoreOS testing-devel
