# Stream-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

# This is the developer default version. In pipelines, this is driven by versionary.
VERSION=43.dev
BUILDER_IMG=quay.io/bootc-devel/fedora-bootc-43-standard@sha256:d4849601dc3f84d87826a1f14c820f27a9d5d1736641dc2b9ec1449144e5c720
MANIFEST=manifest.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=manifests
NAME=fedora-coreos
DESCRIPTION=Fedora CoreOS testing-devel
