---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/testing-farm
transformers:
  - |-
    apiVersion: builtin
    kind: PrefixSuffixTransformer
    metadata:
      name: SuffixTransformer2
    suffix: "-testing-devel"
    fieldSpecs:
    - kind: IntegrationTestScenario
      path: spec/application
    - kind: IntegrationTestScenario
      path: spec/contexts/name
patches:
  - target:
      kind: IntegrationTestScenario
      name: fedora-coreos-kola-tests-x86-64
    patch: |-
      - op: replace
        path: /metadata/name
        value: fedora-coreos-testing-devel-kola-tests-x86-64
  - target:
      kind: IntegrationTestScenario
      name: fedora-coreos-kola-tests-aarch64
    patch: |-
      - op: replace
        path: /metadata/name
        value: fedora-coreos-testing-devel-kola-tests-aarch64

