apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  annotations:
    test.appstudio.openshift.io/finally_timeout: 3h
    test.appstudio.openshift.io/pipeline_timeout: 8h
    test.appstudio.openshift.io/tasks_timeout: 5h
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: fedora-coreos-testing-devel-kola-tests-aarch64
spec:
  application: fedora-coreos-testing-devel
  contexts:
  - name: component_fedora-coreos-testing-devel
  params:
  - name: ARCH
    value: aarch64
  - name: IMAGE_TAG
    value: v3.16
  - name: GIT_URL
    value: https://github.com/Roshan-R/fedora-coreos-config
  - name: GIT_REF
    value: testing-farm-kola
  - name: TMT_PLAN
    value: tmt
  resolverRef:
    params:
    - name: url
      value: https://gitlab.com/testing-farm/integrations-konflux
    - name: revision
      value: v3.16
    - name: pathInRepo
      value: pipeline/tmt-via-testing-farm/tmt-via-testing-farm.yaml
    resolver: git
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  annotations:
    test.appstudio.openshift.io/finally_timeout: 3h
    test.appstudio.openshift.io/pipeline_timeout: 8h
    test.appstudio.openshift.io/tasks_timeout: 5h
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: fedora-coreos-testing-devel-kola-tests-x86-64
spec:
  application: fedora-coreos-testing-devel
  contexts:
  - name: component_fedora-coreos-testing-devel
  params:
  - name: ARCH
    value: x86_64
  - name: IMAGE_TAG
    value: v3.16
  - name: GIT_URL
    value: https://github.com/Roshan-R/fedora-coreos-config
  - name: GIT_REF
    value: testing-farm-kola
  - name: TMT_PLAN
    value: tmt
  resolverRef:
    params:
    - name: url
      value: https://gitlab.com/testing-farm/integrations-konflux
    - name: revision
      value: v3.16
    - name: pathInRepo
      value: pipeline/tmt-via-testing-farm/tmt-via-testing-farm.yaml
    resolver: git
